### ISSUE TITLE
libatiadlxx.so not found

### ISSUE THREAD

**Issue by pszi1ard** [epixoip/od6config#5]
I have the "AMD Catalyst™ 14.12 Proprietary Ubuntu 14.04 x86_64 Video Driver for Graphics Accelerators" driver installed, but the atiadlxx library does not seem to be included in this. Which version of the Catalyst drivers includes this library? Do I need the X version? Do I need X server running?

It would also be beneficial if you could update your README with this info. Thanks!

**Comment by epixoip** [comment]
Depending on what you are doing, you may not want to use 14.12. It is known to be broken. You probably want to use 14.9 instead. Yes, X server needs to be running to use ADL. ADL can only communicate via X11. Please refer to http://hashcat.net/wiki/doku.php?id=linux_server_howto

**Comment by pszi1ard** [comment]
Thanks for the info. In what way is 14.12 broken? I intend to use a Hawaii device for compute only on a headless server, that's why I'd prefer no X server. Does the X server need to be running at all times or can it be shut down after e.g. changing clocks?

**Comment by epixoip** [comment]
14.12 is broken with compute. See the following:

http://hashcat.net/forum/thread-3915.html
http://hashcat.net/forum/thread-3900-post-22133.html#pid22133
http://hashcat.net/forum/thread-4186-post-23873.html#pid23873

Yes, the X server needs to be running at all times, even on a headless server. Otherwise you will have no control over the GPU and will be relying on the card's firmware to control the device, which does not work well for compute at all. I realize this seems less than ideal, but it's how it has to be done.

**Comment by pszi1ard** [comment]
Thanks for the info, much appreciated.
